// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjetoES.API.Data;

#nullable disable

namespace ProjetoES.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523170452_ListaPessoalManyToMany")]
    partial class ListaPessoalManyToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ListaPessoalFilme", b =>
                {
                    b.Property<int>("ListaPessoalId")
                        .HasColumnType("integer");

                    b.Property<int>("FilmeId")
                        .HasColumnType("integer");

                    b.HasKey("ListaPessoalId", "FilmeId");

                    b.HasIndex("FilmeId");

                    b.ToTable("ListaPessoalFilme", (string)null);
                });

            modelBuilder.Entity("ProjetoES.API.Models.Acesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAquisicao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int>("FestivalId")
                        .HasColumnType("integer");

                    b.Property<int>("FilmeId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoAcesso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FilmeId");

                    b.ToTable("Acessos");
                });

            modelBuilder.Entity("ProjetoES.API.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Classificacao")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FilmeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsReportado")
                        .HasColumnType("boolean");

                    b.Property<string>("MotivoReporte")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FilmeId");

                    b.HasIndex("ClienteId", "FilmeId")
                        .IsUnique();

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("ProjetoES.API.Models.Carrinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Carrinhos");
                });

            modelBuilder.Entity("ProjetoES.API.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetodoPagamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenciaPagamento")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("integer");

                    b.Property<double>("ValorTotal")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("ProjetoES.API.Models.Festival", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Festivais");
                });

            modelBuilder.Entity("ProjetoES.API.Models.FestivalFilme", b =>
                {
                    b.Property<int>("FestivalId")
                        .HasColumnType("integer")
                        .HasColumnName("FestivaisId");

                    b.Property<int>("FilmeId")
                        .HasColumnType("integer")
                        .HasColumnName("FilmesId");

                    b.Property<decimal>("PrecoBilhete")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("FestivalId", "FilmeId");

                    b.HasIndex("FilmeId");

                    b.ToTable("FestivalFilme", (string)null);
                });

            modelBuilder.Entity("ProjetoES.API.Models.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Elenco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FestivalId")
                        .HasColumnType("integer");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("MediaAvaliacao")
                        .HasColumnType("double precision");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Realizador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sinopse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrailerUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Filmes");
                });

            modelBuilder.Entity("ProjetoES.API.Models.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarrinhoId")
                        .HasColumnType("integer");

                    b.Property<int?>("CompraId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FestivalId")
                        .HasColumnType("integer");

                    b.Property<int>("FilmeId")
                        .HasColumnType("integer");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<double>("PrecoUnitario")
                        .HasColumnType("double precision");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoAcesso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CarrinhoId");

                    b.HasIndex("CompraId");

                    b.HasIndex("FestivalId");

                    b.HasIndex("FilmeId");

                    b.HasIndex("PedidoId");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("ProjetoES.API.Models.ListaPessoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MembroId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MembroId");

                    b.ToTable("ListaPessoais");
                });

            modelBuilder.Entity("ProjetoES.API.Models.LogAlteracaoAcesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcessoId")
                        .HasColumnType("integer");

                    b.Property<int?>("AdministradorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstadoAnterior")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoNovo")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .HasColumnType("text");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AcessoId");

                    b.HasIndex("AdministradorId");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("LogsAlteracaoAcessos");
                });

            modelBuilder.Entity("ProjetoES.API.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<double>("PrecoTotal")
                        .HasColumnType("double precision");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int?>("SessaoId")
                        .HasColumnType("integer");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SessaoId");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("ProjetoES.API.Models.Sessao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FestivalId")
                        .HasColumnType("integer");

                    b.Property<int>("FilmeId")
                        .HasColumnType("integer");

                    b.Property<string>("Sala")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FestivalId");

                    b.HasIndex("FilmeId");

                    b.ToTable("Sessoes");
                });

            modelBuilder.Entity("ProjetoES.API.Models.UtilizadorBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsLogged")
                        .HasColumnType("boolean");

                    b.Property<string>("MetodoPagamento")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimeiroNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UltimoNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Utilizadores", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("UtilizadorBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProjetoES.API.Models.Administrador", b =>
                {
                    b.HasBaseType("ProjetoES.API.Models.UtilizadorBase");

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("ProjetoES.API.Models.Utilizador", b =>
                {
                    b.HasBaseType("ProjetoES.API.Models.UtilizadorBase");

                    b.Property<DateTime?>("DataPrimeiraCompra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataPromocaoAdmin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Utilizador");
                });

            modelBuilder.Entity("ProjetoES.API.Models.Visitante", b =>
                {
                    b.HasBaseType("ProjetoES.API.Models.UtilizadorBase");

                    b.HasDiscriminator().HasValue("Visitante");
                });

            modelBuilder.Entity("ProjetoES.API.Models.Membro", b =>
                {
                    b.HasBaseType("ProjetoES.API.Models.Utilizador");

                    b.HasDiscriminator().HasValue("Membro");
                });

            modelBuilder.Entity("ListaPessoalFilme", b =>
                {
                    b.HasOne("ProjetoES.API.Models.Filme", null)
                        .WithMany()
                        .HasForeignKey("FilmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoES.API.Models.ListaPessoal", null)
                        .WithMany()
                        .HasForeignKey("ListaPessoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoES.API.Models.Acesso", b =>
                {
                    b.HasOne("ProjetoES.API.Models.Utilizador", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoES.API.Models.Filme", "Filme")
                        .WithMany()
                        .HasForeignKey("FilmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Filme");
                });

            modelBuilder.Entity("ProjetoES.API.Models.Avaliacao", b =>
                {
                    b.HasOne("ProjetoES.API.Models.Utilizador", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoES.API.Models.Filme", "Filme")
                        .WithMany()
                        .HasForeignKey("FilmeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Filme");
                });

            modelBuilder.Entity("ProjetoES.API.Models.FestivalFilme", b =>
                {
                    b.HasOne("ProjetoES.API.Models.Festival", "Festival")
                        .WithMany()
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoES.API.Models.Filme", "Filme")
                        .WithMany()
                        .HasForeignKey("FilmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Festival");

                    b.Navigation("Filme");
                });

            modelBuilder.Entity("ProjetoES.API.Models.ItemPedido", b =>
                {
                    b.HasOne("ProjetoES.API.Models.Carrinho", "Carrinho")
                        .WithMany("Itens")
                        .HasForeignKey("CarrinhoId");

                    b.HasOne("ProjetoES.API.Models.Compra", "Compra")
                        .WithMany("Itens")
                        .HasForeignKey("CompraId");

                    b.HasOne("ProjetoES.API.Models.Festival", "Festival")
                        .WithMany()
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoES.API.Models.Filme", "Filme")
                        .WithMany()
                        .HasForeignKey("FilmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoES.API.Models.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId");

                    b.Navigation("Carrinho");

                    b.Navigation("Compra");

                    b.Navigation("Festival");

                    b.Navigation("Filme");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("ProjetoES.API.Models.ListaPessoal", b =>
                {
                    b.HasOne("ProjetoES.API.Models.Utilizador", "Utilizador")
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("ProjetoES.API.Models.LogAlteracaoAcesso", b =>
                {
                    b.HasOne("ProjetoES.API.Models.Acesso", "Acesso")
                        .WithMany()
                        .HasForeignKey("AcessoId");

                    b.HasOne("ProjetoES.API.Models.Administrador", "Administrador")
                        .WithMany()
                        .HasForeignKey("AdministradorId");

                    b.HasOne("ProjetoES.API.Models.Utilizador", "Utilizador")
                        .WithMany()
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acesso");

                    b.Navigation("Administrador");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("ProjetoES.API.Models.Pedido", b =>
                {
                    b.HasOne("ProjetoES.API.Models.Sessao", "Sessao")
                        .WithMany()
                        .HasForeignKey("SessaoId");

                    b.HasOne("ProjetoES.API.Models.Utilizador", "Utilizador")
                        .WithMany("HistoricoCompras")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sessao");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("ProjetoES.API.Models.Sessao", b =>
                {
                    b.HasOne("ProjetoES.API.Models.Festival", "Festival")
                        .WithMany()
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoES.API.Models.Filme", "Filme")
                        .WithMany()
                        .HasForeignKey("FilmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Festival");

                    b.Navigation("Filme");
                });

            modelBuilder.Entity("ProjetoES.API.Models.Utilizador", b =>
                {
                    b.OwnsOne("ProjetoES.API.Models.Morada", "MoradaFaturacao", b1 =>
                        {
                            b1.Property<int>("UtilizadorId")
                                .HasColumnType("integer");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Morada_CodigoPostal");

                            b1.Property<string>("Localidade")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Morada_Localidade");

                            b1.Property<string>("MoradaFaturacao")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Morada_MoradaFaturacao");

                            b1.Property<string>("NomeDestinatario")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Morada_NomeDestinatario");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Morada_Pais");

                            b1.HasKey("UtilizadorId");

                            b1.ToTable("Utilizadores");

                            b1.WithOwner()
                                .HasForeignKey("UtilizadorId");
                        });

                    b.Navigation("MoradaFaturacao");
                });

            modelBuilder.Entity("ProjetoES.API.Models.Carrinho", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ProjetoES.API.Models.Compra", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ProjetoES.API.Models.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ProjetoES.API.Models.Utilizador", b =>
                {
                    b.Navigation("HistoricoCompras");
                });
#pragma warning restore 612, 618
        }
    }
}
