using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ProjetoES.API.Migrations
{
    /// <inheritdoc />
    public partial class AjustarVisitanteMembroFluxo : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "UltimoNome",
                table: "Visitantes",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<string>(
                name: "PrimeiroNome",
                table: "Visitantes",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<string>(
                name: "PasswordHash",
                table: "Visitantes",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<string>(
                name: "Email",
                table: "Visitantes",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text");

            // Ensure column exists (safeguard for schema drift)
            migrationBuilder.Sql(
                "ALTER TABLE \"Filmes\" ADD COLUMN IF NOT EXISTS \"MediaAvaliacao\" double precision NOT NULL DEFAULT 0.0;");

            // Create Avaliacoes table only if it does not already exist (safeguard for schema drift)
            migrationBuilder.Sql("CREATE TABLE IF NOT EXISTS \"Avaliacoes\" (\"Id\" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"ClienteID\" integer NOT NULL, \"FilmeID\" integer NOT NULL, \"Nota\" integer NOT NULL, \"Comentario\" text NOT NULL, \"DataAvaliacao\" timestamp with time zone NOT NULL, \"IsReportado\" boolean NOT NULL); CREATE INDEX IF NOT EXISTS \"IX_Avaliacoes_FilmeID\" ON \"Avaliacoes\" (\"FilmeID\");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Avaliacoes");

            migrationBuilder.DropColumn(
                name: "MediaAvaliacao",
                table: "Filmes");

            migrationBuilder.AlterColumn<string>(
                name: "UltimoNome",
                table: "Visitantes",
                type: "text",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "PrimeiroNome",
                table: "Visitantes",
                type: "text",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "PasswordHash",
                table: "Visitantes",
                type: "text",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "Email",
                table: "Visitantes",
                type: "text",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);
        }
    }
}
