--
-- PostgreSQL database dump
--

\restrict uHd6hdqB3ra3dUJx8skwQspKFFm3cnUQLjLQo2urc2N25wOY2oa3Y6WO9yD7dXd

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Acessos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Acessos" (
    "Id" integer NOT NULL,
    "ClienteId" integer NOT NULL,
    "FilmeId" integer NOT NULL,
    "DataAquisicao" timestamp with time zone NOT NULL,
    "DataValidade" timestamp with time zone,
    "Estado" integer NOT NULL,
    "TipoAcesso" text NOT NULL,
    "FestivalId" integer DEFAULT 0 NOT NULL
);


ALTER TABLE public."Acessos" OWNER TO postgres;

--
-- Name: Acessos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Acessos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Acessos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Avaliacoes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Avaliacoes" (
    "Id" integer NOT NULL,
    "ClienteId" integer NOT NULL,
    "FilmeId" integer NOT NULL,
    "Classificacao" integer NOT NULL,
    "Comentario" text NOT NULL,
    "DataAvaliacao" timestamp with time zone NOT NULL,
    "IsReportado" boolean NOT NULL,
    "MotivoReporte" text
);


ALTER TABLE public."Avaliacoes" OWNER TO postgres;

--
-- Name: Avaliacoes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Avaliacoes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Avaliacoes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Carrinhos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Carrinhos" (
    "Id" integer NOT NULL,
    "UtilizadorId" integer NOT NULL,
    "DataCriacao" timestamp with time zone NOT NULL
);


ALTER TABLE public."Carrinhos" OWNER TO postgres;

--
-- Name: Carrinhos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Carrinhos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Carrinhos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Compras; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Compras" (
    "Id" integer NOT NULL,
    "UtilizadorId" integer NOT NULL,
    "DataCompra" timestamp with time zone NOT NULL,
    "ValorTotal" double precision NOT NULL,
    "MetodoPagamento" text NOT NULL,
    "ReferenciaPagamento" text,
    "Status" text NOT NULL
);


ALTER TABLE public."Compras" OWNER TO postgres;

--
-- Name: Compras_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Compras" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Compras_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Festivais; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Festivais" (
    "Id" integer NOT NULL,
    "Nome" text NOT NULL,
    "DataInicio" date NOT NULL,
    "DataFim" date NOT NULL,
    "Estado" integer NOT NULL,
    "Descricao" text NOT NULL,
    "Local" text NOT NULL
);


ALTER TABLE public."Festivais" OWNER TO postgres;

--
-- Name: Festivais_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Festivais" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Festivais_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: FestivalFilme; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."FestivalFilme" (
    "FestivaisId" integer NOT NULL,
    "FilmesId" integer NOT NULL,
    "PrecoBilhete" numeric(10,2) NOT NULL
);


ALTER TABLE public."FestivalFilme" OWNER TO postgres;

--
-- Name: Filmes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Filmes" (
    "Id" integer NOT NULL,
    "Titulo" text NOT NULL,
    "Sinopse" text NOT NULL,
    "Genero" text NOT NULL,
    "Ano" integer NOT NULL,
    "DuracaoMinutos" integer NOT NULL,
    "MediaAvaliacao" double precision NOT NULL,
    "PosterUrl" text NOT NULL,
    "TrailerUrl" text NOT NULL,
    "Realizador" text NOT NULL,
    "Elenco" text NOT NULL,
    "FestivalId" integer NOT NULL
);


ALTER TABLE public."Filmes" OWNER TO postgres;

--
-- Name: Filmes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Filmes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Filmes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Itens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Itens" (
    "Id" integer NOT NULL,
    "FilmeId" integer,
    "FestivalId" integer NOT NULL,
    "Quantidade" integer NOT NULL,
    "TipoAcesso" text NOT NULL,
    "PrecoUnitario" double precision NOT NULL,
    "Status" text NOT NULL,
    "DataCriacao" timestamp with time zone NOT NULL,
    "CarrinhoId" integer,
    "CompraId" integer,
    "PedidoId" integer
);


ALTER TABLE public."Itens" OWNER TO postgres;

--
-- Name: Itens_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Itens" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Itens_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ListaPessoais; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ListaPessoais" (
    "Id" integer NOT NULL,
    "Tipo" integer NOT NULL,
    "MembroId" integer NOT NULL
);


ALTER TABLE public."ListaPessoais" OWNER TO postgres;

--
-- Name: ListaPessoais_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ListaPessoais" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ListaPessoais_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ListaPessoalFilme; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ListaPessoalFilme" (
    "ListaPessoalId" integer NOT NULL,
    "FilmeId" integer NOT NULL
);


ALTER TABLE public."ListaPessoalFilme" OWNER TO postgres;

--
-- Name: LogsAlteracaoAcessos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."LogsAlteracaoAcessos" (
    "Id" integer NOT NULL,
    "UtilizadorId" integer NOT NULL,
    "DataAlteracao" timestamp with time zone NOT NULL,
    "AcessoId" integer,
    "AdministradorId" integer,
    "EstadoAnterior" integer NOT NULL,
    "EstadoNovo" integer NOT NULL,
    "Motivo" text
);


ALTER TABLE public."LogsAlteracaoAcessos" OWNER TO postgres;

--
-- Name: LogsAlteracaoAcessos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."LogsAlteracaoAcessos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."LogsAlteracaoAcessos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Pedidos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Pedidos" (
    "Id" integer NOT NULL,
    "UtilizadorId" integer NOT NULL,
    "DataPedido" timestamp with time zone NOT NULL,
    "DataPagamento" timestamp with time zone,
    "SessaoId" integer,
    "Quantidade" integer NOT NULL,
    "PrecoTotal" double precision NOT NULL,
    "Estado" integer NOT NULL
);


ALTER TABLE public."Pedidos" OWNER TO postgres;

--
-- Name: Pedidos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Pedidos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Pedidos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Sessoes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Sessoes" (
    "Id" integer NOT NULL,
    "FestivalId" integer NOT NULL,
    "FilmeId" integer NOT NULL,
    "DataInicio" timestamp with time zone NOT NULL,
    "DataFim" timestamp with time zone NOT NULL,
    "Sala" text NOT NULL,
    "Tipo" integer NOT NULL
);


ALTER TABLE public."Sessoes" OWNER TO postgres;

--
-- Name: Sessoes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Sessoes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Sessoes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Utilizadores; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Utilizadores" (
    "Id" integer NOT NULL,
    "IsLogged" boolean NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "PrimeiroNome" text NOT NULL,
    "UltimoNome" text NOT NULL,
    "MetodoPagamento" text,
    "Discriminator" character varying(21) NOT NULL,
    "Tipo" integer,
    "Morada_NomeDestinatario" text,
    "Morada_MoradaFaturacao" text,
    "Morada_CodigoPostal" text,
    "Morada_Localidade" text,
    "Morada_Pais" text,
    "DataPrimeiraCompra" timestamp with time zone,
    "DataPromocaoAdmin" timestamp with time zone
);


ALTER TABLE public."Utilizadores" OWNER TO postgres;

--
-- Name: Utilizadores_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Utilizadores" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Utilizadores_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Acessos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Acessos" ("Id", "ClienteId", "FilmeId", "DataAquisicao", "DataValidade", "Estado", "TipoAcesso", "FestivalId") FROM stdin;
1	2	1	2026-05-23 19:26:26.811588+01	\N	0	Passe completo	1
2	2	3	2026-05-23 19:38:38.443724+01	2026-06-22 19:38:38.443724+01	0	Bilhete de Sessão	1
3	4	1	2026-05-24 03:16:35.19586+01	\N	0	Passe completo	1
4	4	3	2026-05-24 03:16:35.19586+01	\N	0	Passe completo	1
7	4	8	2026-05-24 03:16:35.19586+01	\N	0	Passe completo	1
8	5	1	2026-05-24 03:27:53.626358+01	2026-06-23 03:27:53.626358+01	0	Bilhete de Sessão	1
9	5	3	2026-05-24 03:28:20.101333+01	2026-06-23 03:28:20.101333+01	0	Bilhete de Sessão	1
\.


--
-- Data for Name: Avaliacoes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Avaliacoes" ("Id", "ClienteId", "FilmeId", "Classificacao", "Comentario", "DataAvaliacao", "IsReportado", "MotivoReporte") FROM stdin;
4	5	1	6	adorei	2026-05-24 13:40:02.621908+01	f	\N
5	1	1	1	Filme vai contra as morais LGBTQ+	2026-05-24 13:46:50.745346+01	t	Informação falsa
6	1	9	10	Adorei a parte em que o spongebob fica amigo do patrick.	2026-05-24 13:49:13.389682+01	f	\N
\.


--
-- Data for Name: Carrinhos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Carrinhos" ("Id", "UtilizadorId", "DataCriacao") FROM stdin;
1	2	2026-05-23 18:34:23.052791+01
2	4	2026-05-24 03:11:36.889566+01
3	5	2026-05-24 03:27:41.41771+01
4	1	2026-05-24 13:11:01.3357+01
\.


--
-- Data for Name: Compras; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Compras" ("Id", "UtilizadorId", "DataCompra", "ValorTotal", "MetodoPagamento", "ReferenciaPagamento", "Status") FROM stdin;
\.


--
-- Data for Name: Festivais; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Festivais" ("Id", "Nome", "DataInicio", "DataFim", "Estado", "Descricao", "Local") FROM stdin;
1	Festival da Bolacha	2026-05-22	2026-05-30	1	awdawdaw	Madeira
2	Festival da Cebola	2026-05-22	2026-05-29	0	awdawd	Porto
3	Festival Cabouco	2027-02-12	2027-03-12	0	Festival Anual do Cabouco na cidade do Cabouco.	Cabouco
4	Festival do Sol	2003-04-12	2003-05-12	3	Festival do Sol	Ilha do Sol
\.


--
-- Data for Name: FestivalFilme; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."FestivalFilme" ("FestivaisId", "FilmesId", "PrecoBilhete") FROM stdin;
2	2	0.00
2	3	0.00
2	4	0.00
1	1	5.50
1	3	5.00
2	5	0.00
2	8	0.00
1	8	2.00
4	1	12.00
4	2	22.00
3	9	12.00
3	10	11.00
\.


--
-- Data for Name: Filmes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Filmes" ("Id", "Titulo", "Sinopse", "Genero", "Ano", "DuracaoMinutos", "MediaAvaliacao", "PosterUrl", "TrailerUrl", "Realizador", "Elenco", "FestivalId") FROM stdin;
1	Matrix	Thomas Anderson é um jovem programador que, fora das horas de serviço, dá pelo nome de Neo, um «hacker».  Ele sempre percebeu que algo no mundo não estava bem. A esperança de encontrar as respostas que procura leva-o a seguir o «coelho branco». E depois, a vida dele nunca mais será a mesma.	Ação, Ficção científica	1999	136	0	https://image.tmdb.org/t/p/w500/lDqMDI3xpbB9UQRyeXfei0MXhqb.jpg	https://www.youtube.com/embed/d0XTFAMmhrE	Lana Wachowski	Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving, Gloria Foster	0
2	Shrek	Em um pântano distante vive Shrek, um ogre solitário que vê, sem mais nem menos, a sua vida ser invadida por uma série de personagens de contos de fada, como um grande e malvado lobo, três porcos que não têm casa, entre outros. Todos eles foram expulsos das suas casas pelo malvado Lorde Farquaad. Determinado a recuperar a tranquilidade de antes, Shrek resolve encontrar Farquaad e faz um acordo com ele: todos os poderão voltar às suas casas se ele e o seu amigo Burro resgatarem uma bela princesa, que é prisioneira de um dragão. Porém, quando Shrek e o Burro conseguem finalmente resgatar a princesa descobrem que os seus problemas estão apenas a começar.	Animação, Comédia, Fantasia, Aventura, Família	2001	90	0	https://image.tmdb.org/t/p/w500/wxeqfC221YMptRRdzxlijAh7q8l.jpg	https://www.youtube.com/embed/ppDwfm6e498	Andrew Adamson	Mike Myers, Eddie Murphy, Cameron Diaz, John Lithgow, Vincent Cassel	0
3	Interstellar	Com o nosso tempo no planeta Terra a aproximar-se do fim, uma equipa de exploradores é enviada na missão mais importante da história da humanidade: viajar para além da nossa galáxia para descobrir se a humanidade tem futuro entre as estrelas.	Aventura, Drama, Ficção científica	2014	169	0	https://image.tmdb.org/t/p/w500/6ricSDD83BClJsFdGB6x7cM0MFQ.jpg	https://www.youtube.com/embed/LY19rHKAaAg	Christopher Nolan	Matthew McConaughey, Anne Hathaway, Michael Caine, Jessica Chastain, Casey Affleck	0
4	Shrek 2	Após casar-se com a Princesa Fiona, Shrek vive feliz no seu pântano. Ao voltar da sua lua-de-mel, Fiona recebe uma carta dos seus pais, que não sabem que ela agora é um ogre, convidando-a para um jantar juntamente com o seu grande amor, na intenção de conhecê-lo. A muito custo, Fiona consegue convencer Shrek a ir visitá-los, tendo ainda a companhia do Burro. Porém os problemas começam quando os pais de Fiona descobrem que ela não se casou com o Príncipe, a quem havia sido prometida, e enviam o Gato de Botas para separá-los.	Animação, Comédia, Família, Fantasia, Romance	2004	92	0	https://image.tmdb.org/t/p/w500/2yYP0PQjG8zVqturh1BAqu2Tixl.jpg	https://www.youtube.com/embed/iuNghO1XsHI	Conrad Vernon	Mike Myers, Eddie Murphy, Cameron Diaz, Julie Andrews, Antonio Banderas	0
5	Rocky	Rocky Balboa é um aspirante a lutador de boxe que trabalha numa fábrica de carnes e ganha um extra como cobrador de dívidas. Quando surge a proposta de lutar com o campeão de pesos-pesados Apollo Creed, Rocky acredita ser uma oportunidade única. A missão é quase impossível, mas Rocky vai dar tudo por tudo para alcançar a vitória e ao mesmo tempo conquistar Adrian, a tímida funcionária da loja de animais...	Drama	1976	119	0	https://image.tmdb.org/t/p/w500/b9B1DXcPNsJfTtc4x2LKA3bykoJ.jpg	https://www.youtube.com/embed/-Hk-LYcavrw	John G. Avildsen	Sylvester Stallone, Talia Shire, Burt Young, Carl Weathers, Burgess Meredith	0
8	Rocky II	Após vencer o campeão Apollo Creed, os fãs pedem uma desforra. Mas Rocky sofreu graves ferimentos e afastou-se dos ringues. Agora a sua concentração está toda virada para Adrian, com quem acabou por casar e leva uma vida estável. Porém, o chamamento do ringue é mais forte, e quando Apollo o pressiona para um combate, Rocky retoma os treinos. Será que Rocky vai sair mais uma vez vitorioso?	Drama	1979	119	0	https://image.tmdb.org/t/p/w500/pkZ7uAeA37bLS5cos8w8uEF8K5b.jpg	https://www.youtube.com/embed/yZrmRBj1r_E	Sylvester Stallone	Sylvester Stallone, Talia Shire, Burt Young, Carl Weathers, Burgess Meredith	0
9	SpongeBob - Esponja em Missão	Depois de Gary, o adorado caracol de estimação de SpongeBob, ter sido capturado, SpongeBob e Patrick embarcam numa épica aventura para A Cidade Perdida de Atlantic City para trazerem Gary de volta a casa. Enquanto navegam pelos encantos e perigos desta hilariante missão de resgate, SpongeBob e os seus amigos provam que não existe nada mais forte que o poder da amizade.	Aventura, Animação, Comédia, Família, Fantasia	2020	91	0	https://image.tmdb.org/t/p/w500/744ZoymAp95NN9ZGXdXgmpxTd7H.jpg	https://www.youtube.com/embed/s4TAfaddV4w	Tim Hill	Tom Kenny, Bill Fagerbakke, Rodger Bumpass, Mr. Lawrence, Keanu Reeves	0
10	À Procura de Nemo	A vida pode ser muito perigosa no Grande Recife para um pequeno peixinho. E quando o super protector Marlin vê o filho Nemo ser capturado por mergulhadores enquanto ambos estavam a meio de uma discussão, tem de pôr de lado os seus medos mais profundos e embrenhar-se no enorme oceano em busca da sua pequena cria. Felizmente, Marlin vai poder contar com a ajuda de Dory, uma peixinha optimista mas muito, muito, muito esquecida. Nessa viagem à procura de Nemo, Marlin e Dory cruzam-se com todo o tipo de criaturas, entre eles tubarões vegetarianos, tartarugas surfistas e gaivotas esfomeadas. Com realização de Andrew Stanton e Lee Unkrich, esta grande produção da Pixar/Disney teve quatro nomeações para os Óscares, vencendo na categoria de melhor filme de animação.	Animação, Família, Aventura	2003	96	0	https://image.tmdb.org/t/p/w500/xCvzutPTpSRPIQAirqQTMV3JIMa.jpg	https://www.youtube.com/embed/SPHfeNgogVs	Andrew Stanton	Albert Brooks, Ellen DeGeneres, Alexander Gould, Willem Dafoe, Geoffrey Rush	0
\.


--
-- Data for Name: Itens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Itens" ("Id", "FilmeId", "FestivalId", "Quantidade", "TipoAcesso", "PrecoUnitario", "Status", "DataCriacao", "CarrinhoId", "CompraId", "PedidoId") FROM stdin;
2	3	1	1	Bilhete de Sessão	5	Carrinho	2026-05-23 19:01:38.375581+01	\N	\N	\N
1	1	1	1	Passe Completo	0	Carrinho	2026-05-23 18:34:23.144162+01	\N	\N	\N
4	1	1	1	Passe Completo	15.05	Pedido	2026-05-23 19:26:26.767406+01	\N	\N	1
6	3	1	1	Bilhete de Sessão	5	Pedido	2026-05-23 19:38:38.373693+01	\N	\N	2
8	1	1	1	Passe Diário	10.75	Pedido	2026-05-24 03:16:35.17078+01	\N	\N	23
9	2	2	1	Passe Diário	0	Carrinho	2026-05-24 03:24:02.767062+01	2	\N	\N
11	1	1	1	Bilhete de Sessão	5.5	Pedido	2026-05-24 03:27:53.547268+01	\N	\N	24
13	3	1	1	Bilhete de Sessão	5	Pedido	2026-05-24 03:28:20.097115+01	\N	\N	25
\.


--
-- Data for Name: ListaPessoais; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ListaPessoais" ("Id", "Tipo", "MembroId") FROM stdin;
3	0	1
1	1	1
2	2	1
4	0	2
5	1	2
6	2	2
7	1	5
8	0	5
9	2	5
\.


--
-- Data for Name: ListaPessoalFilme; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ListaPessoalFilme" ("ListaPessoalId", "FilmeId") FROM stdin;
3	8
1	8
2	8
1	4
3	4
1	3
2	3
4	3
5	3
6	3
7	1
8	1
9	1
\.


--
-- Data for Name: LogsAlteracaoAcessos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."LogsAlteracaoAcessos" ("Id", "UtilizadorId", "DataAlteracao", "AcessoId", "AdministradorId", "EstadoAnterior", "EstadoNovo", "Motivo") FROM stdin;
\.


--
-- Data for Name: Pedidos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Pedidos" ("Id", "UtilizadorId", "DataPedido", "DataPagamento", "SessaoId", "Quantidade", "PrecoTotal", "Estado") FROM stdin;
1	2	2026-05-23 19:26:26.767587+01	2026-05-23 19:26:26.767654+01	\N	0	15.05	1
2	2	2026-05-23 19:38:38.373865+01	2026-05-23 19:38:38.37391+01	\N	0	5	1
23	4	2026-05-24 03:16:35.170781+01	2026-05-24 03:16:35.170781+01	\N	0	10.75	1
24	5	2026-05-24 03:27:53.547338+01	2026-05-24 03:27:53.547353+01	\N	0	5.5	1
25	5	2026-05-24 03:28:20.097117+01	2026-05-24 03:28:20.097117+01	\N	0	5	1
\.


--
-- Data for Name: Sessoes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Sessoes" ("Id", "FestivalId", "FilmeId", "DataInicio", "DataFim", "Sala", "Tipo") FROM stdin;
\.


--
-- Data for Name: Utilizadores; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Utilizadores" ("Id", "IsLogged", "Email", "PasswordHash", "PrimeiroNome", "UltimoNome", "MetodoPagamento", "Discriminator", "Tipo", "Morada_NomeDestinatario", "Morada_MoradaFaturacao", "Morada_CodigoPostal", "Morada_Localidade", "Morada_Pais", "DataPrimeiraCompra", "DataPromocaoAdmin") FROM stdin;
2	t	andre@gmail.com	$2a$11$OLD0N15wjOpcqFS77Fi2nOCtVKJOlT2f2Ae15BWyw.PlvBV.EVuVK	André	Pereira	\N	Utilizador	2	\N	\N	\N	\N	\N	2026-05-23 19:26:26.861602+01	\N
3	t	teste@gmail.com	$2a$11$j7jkEThg0QKLrIPae8GaU.AIGd.YHnRJQGQcUD1DSb2jsVsq43.RS	teste		\N	Utilizador	1	\N	\N	\N	\N	\N	\N	\N
4	t	madeiras1@email.com	$2a$11$fWsTT/qPvWPDRT8Prrjh9.oaDfm6/yKaUVytcL3341qtwVGUVY6lC	q31231	312312	\N	Utilizador	2	\N	\N	\N	\N	\N	2026-05-24 03:16:35.250742+01	\N
5	t	madeiras@email.com	$2a$11$Cm87QguyFBvtOlDhkvqqqe1r62i7Z15Cte2/4zZ85bmRx5xVPBdri	rwrwe	rwerewr	\N	Utilizador	2	\N	\N	\N	\N	\N	2026-05-24 03:27:53.68906+01	\N
1	t	admin@festival.com	$2a$11$gA4uSF28NLT3YccuupSsyeAzeSnhaOPjTzx62YR9KzhrwoNa8X1ly	Administrador	Principal	\N	Utilizador	3	\N	\N	\N	\N	\N	\N	2026-05-23 17:52:27.250071+01
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260515151246_InitialCreate	10.0.7
20260515162413_AddLocalToFestival	10.0.7
20260516140526_TornarSessaoIdNullable	10.0.7
20260518071343_AddMotivoReporteToAvaliacao	10.0.7
20260523133220_FixListaPessoalFK	10.0.7
20260523151321_AddFestivalIdToAcesso	10.0.7
20260523170452_ListaPessoalManyToMany	10.0.7
20260524013730_MakeItemPedidoFilmeIdNullable	10.0.7
\.


--
-- Name: Acessos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Acessos_Id_seq"', 9, true);


--
-- Name: Avaliacoes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Avaliacoes_Id_seq"', 6, true);


--
-- Name: Carrinhos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Carrinhos_Id_seq"', 4, true);


--
-- Name: Compras_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Compras_Id_seq"', 1, false);


--
-- Name: Festivais_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Festivais_Id_seq"', 4, true);


--
-- Name: Filmes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Filmes_Id_seq"', 10, true);


--
-- Name: Itens_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Itens_Id_seq"', 13, true);


--
-- Name: ListaPessoais_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ListaPessoais_Id_seq"', 9, true);


--
-- Name: LogsAlteracaoAcessos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."LogsAlteracaoAcessos_Id_seq"', 1, false);


--
-- Name: Pedidos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Pedidos_Id_seq"', 25, true);


--
-- Name: Sessoes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Sessoes_Id_seq"', 1, false);


--
-- Name: Utilizadores_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Utilizadores_Id_seq"', 5, true);


--
-- Name: Acessos PK_Acessos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Acessos"
    ADD CONSTRAINT "PK_Acessos" PRIMARY KEY ("Id");


--
-- Name: Avaliacoes PK_Avaliacoes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Avaliacoes"
    ADD CONSTRAINT "PK_Avaliacoes" PRIMARY KEY ("Id");


--
-- Name: Carrinhos PK_Carrinhos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Carrinhos"
    ADD CONSTRAINT "PK_Carrinhos" PRIMARY KEY ("Id");


--
-- Name: Compras PK_Compras; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Compras"
    ADD CONSTRAINT "PK_Compras" PRIMARY KEY ("Id");


--
-- Name: Festivais PK_Festivais; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Festivais"
    ADD CONSTRAINT "PK_Festivais" PRIMARY KEY ("Id");


--
-- Name: FestivalFilme PK_FestivalFilme; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."FestivalFilme"
    ADD CONSTRAINT "PK_FestivalFilme" PRIMARY KEY ("FestivaisId", "FilmesId");


--
-- Name: Filmes PK_Filmes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Filmes"
    ADD CONSTRAINT "PK_Filmes" PRIMARY KEY ("Id");


--
-- Name: Itens PK_Itens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Itens"
    ADD CONSTRAINT "PK_Itens" PRIMARY KEY ("Id");


--
-- Name: ListaPessoais PK_ListaPessoais; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ListaPessoais"
    ADD CONSTRAINT "PK_ListaPessoais" PRIMARY KEY ("Id");


--
-- Name: ListaPessoalFilme PK_ListaPessoalFilme; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ListaPessoalFilme"
    ADD CONSTRAINT "PK_ListaPessoalFilme" PRIMARY KEY ("ListaPessoalId", "FilmeId");


--
-- Name: LogsAlteracaoAcessos PK_LogsAlteracaoAcessos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LogsAlteracaoAcessos"
    ADD CONSTRAINT "PK_LogsAlteracaoAcessos" PRIMARY KEY ("Id");


--
-- Name: Pedidos PK_Pedidos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Pedidos"
    ADD CONSTRAINT "PK_Pedidos" PRIMARY KEY ("Id");


--
-- Name: Sessoes PK_Sessoes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sessoes"
    ADD CONSTRAINT "PK_Sessoes" PRIMARY KEY ("Id");


--
-- Name: Utilizadores PK_Utilizadores; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Utilizadores"
    ADD CONSTRAINT "PK_Utilizadores" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Acessos_ClienteId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Acessos_ClienteId" ON public."Acessos" USING btree ("ClienteId");


--
-- Name: IX_Acessos_FilmeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Acessos_FilmeId" ON public."Acessos" USING btree ("FilmeId");


--
-- Name: IX_Avaliacoes_ClienteId_FilmeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Avaliacoes_ClienteId_FilmeId" ON public."Avaliacoes" USING btree ("ClienteId", "FilmeId");


--
-- Name: IX_Avaliacoes_FilmeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Avaliacoes_FilmeId" ON public."Avaliacoes" USING btree ("FilmeId");


--
-- Name: IX_FestivalFilme_FilmesId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_FestivalFilme_FilmesId" ON public."FestivalFilme" USING btree ("FilmesId");


--
-- Name: IX_Itens_CarrinhoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Itens_CarrinhoId" ON public."Itens" USING btree ("CarrinhoId");


--
-- Name: IX_Itens_CompraId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Itens_CompraId" ON public."Itens" USING btree ("CompraId");


--
-- Name: IX_Itens_FestivalId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Itens_FestivalId" ON public."Itens" USING btree ("FestivalId");


--
-- Name: IX_Itens_FilmeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Itens_FilmeId" ON public."Itens" USING btree ("FilmeId");


--
-- Name: IX_Itens_PedidoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Itens_PedidoId" ON public."Itens" USING btree ("PedidoId");


--
-- Name: IX_ListaPessoais_MembroId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ListaPessoais_MembroId" ON public."ListaPessoais" USING btree ("MembroId");


--
-- Name: IX_ListaPessoalFilme_FilmeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ListaPessoalFilme_FilmeId" ON public."ListaPessoalFilme" USING btree ("FilmeId");


--
-- Name: IX_LogsAlteracaoAcessos_AcessoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_LogsAlteracaoAcessos_AcessoId" ON public."LogsAlteracaoAcessos" USING btree ("AcessoId");


--
-- Name: IX_LogsAlteracaoAcessos_AdministradorId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_LogsAlteracaoAcessos_AdministradorId" ON public."LogsAlteracaoAcessos" USING btree ("AdministradorId");


--
-- Name: IX_LogsAlteracaoAcessos_UtilizadorId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_LogsAlteracaoAcessos_UtilizadorId" ON public."LogsAlteracaoAcessos" USING btree ("UtilizadorId");


--
-- Name: IX_Pedidos_SessaoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Pedidos_SessaoId" ON public."Pedidos" USING btree ("SessaoId");


--
-- Name: IX_Pedidos_UtilizadorId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Pedidos_UtilizadorId" ON public."Pedidos" USING btree ("UtilizadorId");


--
-- Name: IX_Sessoes_FestivalId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Sessoes_FestivalId" ON public."Sessoes" USING btree ("FestivalId");


--
-- Name: IX_Sessoes_FilmeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Sessoes_FilmeId" ON public."Sessoes" USING btree ("FilmeId");


--
-- Name: Acessos FK_Acessos_Filmes_FilmeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Acessos"
    ADD CONSTRAINT "FK_Acessos_Filmes_FilmeId" FOREIGN KEY ("FilmeId") REFERENCES public."Filmes"("Id") ON DELETE CASCADE;


--
-- Name: Acessos FK_Acessos_Utilizadores_ClienteId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Acessos"
    ADD CONSTRAINT "FK_Acessos_Utilizadores_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES public."Utilizadores"("Id") ON DELETE RESTRICT;


--
-- Name: Avaliacoes FK_Avaliacoes_Filmes_FilmeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Avaliacoes"
    ADD CONSTRAINT "FK_Avaliacoes_Filmes_FilmeId" FOREIGN KEY ("FilmeId") REFERENCES public."Filmes"("Id") ON DELETE RESTRICT;


--
-- Name: Avaliacoes FK_Avaliacoes_Utilizadores_ClienteId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Avaliacoes"
    ADD CONSTRAINT "FK_Avaliacoes_Utilizadores_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES public."Utilizadores"("Id") ON DELETE RESTRICT;


--
-- Name: FestivalFilme FK_FestivalFilme_Festivais_FestivaisId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."FestivalFilme"
    ADD CONSTRAINT "FK_FestivalFilme_Festivais_FestivaisId" FOREIGN KEY ("FestivaisId") REFERENCES public."Festivais"("Id") ON DELETE CASCADE;


--
-- Name: FestivalFilme FK_FestivalFilme_Filmes_FilmesId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."FestivalFilme"
    ADD CONSTRAINT "FK_FestivalFilme_Filmes_FilmesId" FOREIGN KEY ("FilmesId") REFERENCES public."Filmes"("Id") ON DELETE CASCADE;


--
-- Name: Itens FK_Itens_Carrinhos_CarrinhoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Itens"
    ADD CONSTRAINT "FK_Itens_Carrinhos_CarrinhoId" FOREIGN KEY ("CarrinhoId") REFERENCES public."Carrinhos"("Id");


--
-- Name: Itens FK_Itens_Compras_CompraId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Itens"
    ADD CONSTRAINT "FK_Itens_Compras_CompraId" FOREIGN KEY ("CompraId") REFERENCES public."Compras"("Id");


--
-- Name: Itens FK_Itens_Festivais_FestivalId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Itens"
    ADD CONSTRAINT "FK_Itens_Festivais_FestivalId" FOREIGN KEY ("FestivalId") REFERENCES public."Festivais"("Id") ON DELETE CASCADE;


--
-- Name: Itens FK_Itens_Filmes_FilmeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Itens"
    ADD CONSTRAINT "FK_Itens_Filmes_FilmeId" FOREIGN KEY ("FilmeId") REFERENCES public."Filmes"("Id");


--
-- Name: Itens FK_Itens_Pedidos_PedidoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Itens"
    ADD CONSTRAINT "FK_Itens_Pedidos_PedidoId" FOREIGN KEY ("PedidoId") REFERENCES public."Pedidos"("Id");


--
-- Name: ListaPessoais FK_ListaPessoais_Utilizadores_MembroId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ListaPessoais"
    ADD CONSTRAINT "FK_ListaPessoais_Utilizadores_MembroId" FOREIGN KEY ("MembroId") REFERENCES public."Utilizadores"("Id") ON DELETE CASCADE;


--
-- Name: ListaPessoalFilme FK_ListaPessoalFilme_Filmes_FilmeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ListaPessoalFilme"
    ADD CONSTRAINT "FK_ListaPessoalFilme_Filmes_FilmeId" FOREIGN KEY ("FilmeId") REFERENCES public."Filmes"("Id") ON DELETE CASCADE;


--
-- Name: ListaPessoalFilme FK_ListaPessoalFilme_ListaPessoais_ListaPessoalId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ListaPessoalFilme"
    ADD CONSTRAINT "FK_ListaPessoalFilme_ListaPessoais_ListaPessoalId" FOREIGN KEY ("ListaPessoalId") REFERENCES public."ListaPessoais"("Id") ON DELETE CASCADE;


--
-- Name: LogsAlteracaoAcessos FK_LogsAlteracaoAcessos_Acessos_AcessoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LogsAlteracaoAcessos"
    ADD CONSTRAINT "FK_LogsAlteracaoAcessos_Acessos_AcessoId" FOREIGN KEY ("AcessoId") REFERENCES public."Acessos"("Id");


--
-- Name: LogsAlteracaoAcessos FK_LogsAlteracaoAcessos_Utilizadores_AdministradorId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LogsAlteracaoAcessos"
    ADD CONSTRAINT "FK_LogsAlteracaoAcessos_Utilizadores_AdministradorId" FOREIGN KEY ("AdministradorId") REFERENCES public."Utilizadores"("Id");


--
-- Name: LogsAlteracaoAcessos FK_LogsAlteracaoAcessos_Utilizadores_UtilizadorId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LogsAlteracaoAcessos"
    ADD CONSTRAINT "FK_LogsAlteracaoAcessos_Utilizadores_UtilizadorId" FOREIGN KEY ("UtilizadorId") REFERENCES public."Utilizadores"("Id") ON DELETE CASCADE;


--
-- Name: Pedidos FK_Pedidos_Sessoes_SessaoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Pedidos"
    ADD CONSTRAINT "FK_Pedidos_Sessoes_SessaoId" FOREIGN KEY ("SessaoId") REFERENCES public."Sessoes"("Id");


--
-- Name: Pedidos FK_Pedidos_Utilizadores_UtilizadorId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Pedidos"
    ADD CONSTRAINT "FK_Pedidos_Utilizadores_UtilizadorId" FOREIGN KEY ("UtilizadorId") REFERENCES public."Utilizadores"("Id") ON DELETE RESTRICT;


--
-- Name: Sessoes FK_Sessoes_Festivais_FestivalId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sessoes"
    ADD CONSTRAINT "FK_Sessoes_Festivais_FestivalId" FOREIGN KEY ("FestivalId") REFERENCES public."Festivais"("Id") ON DELETE CASCADE;


--
-- Name: Sessoes FK_Sessoes_Filmes_FilmeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sessoes"
    ADD CONSTRAINT "FK_Sessoes_Filmes_FilmeId" FOREIGN KEY ("FilmeId") REFERENCES public."Filmes"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict uHd6hdqB3ra3dUJx8skwQspKFFm3cnUQLjLQo2urc2N25wOY2oa3Y6WO9yD7dXd

